config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :comments
  resources :photo_restaurants
  resources :stars
  resources :restaurants
  mount_devise_token_auth_for 'User', at: 'auth'
  
  devise_for :administrators

  get '/users', to: 'users#index', as: 'users'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/star.rb
class Star < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  before_action :set_star, only: [:show, :edit, :update, :destroy]

  # GET /stars
  # GET /stars.json
  def index
    @stars = Star.all
  end

  # GET /stars/1
  # GET /stars/1.json
  def show
  end

  # GET /stars/new
  def new
    @star = Star.new
  end

  # GET /stars/1/edit
  def edit
  end

  # POST /stars
  # POST /stars.json
  def create
    @star = Star.new(star_params)

    respond_to do |format|
      if @star.save
        format.html { redirect_to @star, notice: 'Star was successfully created.' }
        format.json { render :show, status: :created, location: @star }
      else
        format.html { render :new }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stars/1
  # PATCH/PUT /stars/1.json
  def update
    respond_to do |format|
      if @star.update(star_params)
        format.html { redirect_to @star, notice: 'Star was successfully updated.' }
        format.json { render :show, status: :ok, location: @star }
      else
        format.html { render :edit }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1
  # DELETE /stars/1.json
  def destroy
    @star.destroy
    respond_to do |format|
      format.html { redirect_to stars_url, notice: 'Star was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_star
      @star = Star.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def star_params
      params.require(:star).permit(:value, :user_id, :restaurant_id)
    end
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/stars/_form.html.erb
<%= form_with(model: star, local: true) do |form| %>
  <% if star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(star.errors.count, "error") %> prohibited this star from being saved:</h2>

      <ul>
      <% star.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :value %>
    <%= form.number_field :value, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :restaurant_id %>
    <%= form.text_field :restaurant_id, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stars/edit.html.erb
<% if signed_in? %>
<h1>Editing Star</h1>

<%= render 'form', star: @star %>

<%= link_to 'Show', @star %> |
<%= link_to 'Back', stars_path %>

<% end %>

app/views/stars/index.html.erb
<% if signed_in? %>
<p id="notice"><%= notice %></p>

<h1>Stars</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Value</th>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stars.each do |star| %>
      <tr>
        <td><%= star.value %></td>
        <td><%= star.user %></td>
        <td><%= star.restaurant.name %></td>
        <td><%= link_to 'Show', star %></td>
        <td><%= link_to 'Edit', edit_star_path(star) %></td>
        <td><%= link_to 'Destroy', star, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Star', new_star_path %>
<% end %>

app/views/stars/new.html.erb
<% if signed_in? %>
<h1>New Star</h1>

<%= render 'form', star: @star %>

<%= link_to 'Back', stars_path %>
<% end %>

app/views/stars/show.html.erb
<% if signed_in? %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @star.value %>
</p>

<p>
  <strong>User:</strong>
  <%= @star.user %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @star.restaurant %>
</p>

<%= link_to 'Edit', edit_star_path(@star) %> |
<%= link_to 'Back', stars_path %>

<% end %>