config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :comments
  resources :photo_restaurants
  resources :stars
  resources :restaurants
  mount_devise_token_auth_for 'User', at: 'auth'
  
  devise_for :administrators

  get '/users', to: 'users#index', as: 'users'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :restaurant

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:day, :start, :end, :restaurant_id)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :day %>
    <%= form.text_field :day, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :start %>
    <%= form.text_field :start, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :end %>
    <%= form.text_field :end, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :restaurant_id %>
    <%= form.text_field :restaurant_id, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<% if signed_in? %>
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

<% end %>

app/views/schedules/index.html.erb
<% if signed_in? %>
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Day</th>
      <th>Start</th>
      <th>End</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.day %></td>
        <td><%= schedule.start %></td>
        <td><%= schedule.end %></td>
        <td><%= schedule.restaurant.name %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>
<% end %>

app/views/schedules/new.html.erb
<% if signed_in? %>
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>
<% end %>

app/views/schedules/show.html.erb
<% if signed_in? %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @schedule.day %>
</p>

<p>
  <strong>Start:</strong>
  <%= @schedule.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @schedule.end %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @schedule.restaurant.name %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

<% end %>