config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :comments
  resources :photo_restaurants
  resources :stars
  resources :restaurants
  mount_devise_token_auth_for 'User', at: 'auth'
  
  devise_for :administrators

  get '/users', to: 'users#index', as: 'users'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo_restaurant.rb
class PhotoRestaurant < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/photo_restaurants_controller.rb
class PhotoRestaurantsController < ApplicationController
  before_action :set_photo_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /photo_restaurants
  # GET /photo_restaurants.json
  def index
    @photo_restaurants = PhotoRestaurant.all
  end

  # GET /photo_restaurants/1
  # GET /photo_restaurants/1.json
  def show
  end

  # GET /photo_restaurants/new
  def new
    @photo_restaurant = PhotoRestaurant.new
  end

  # GET /photo_restaurants/1/edit
  def edit
  end

  # POST /photo_restaurants
  # POST /photo_restaurants.json
  def create
    @photo_restaurant = PhotoRestaurant.new(photo_restaurant_params)

    respond_to do |format|
      if @photo_restaurant.save
        format.html { redirect_to @photo_restaurant, notice: 'Photo restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @photo_restaurant }
      else
        format.html { render :new }
        format.json { render json: @photo_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photo_restaurants/1
  # PATCH/PUT /photo_restaurants/1.json
  def update
    respond_to do |format|
      if @photo_restaurant.update(photo_restaurant_params)
        format.html { redirect_to @photo_restaurant, notice: 'Photo restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo_restaurant }
      else
        format.html { render :edit }
        format.json { render json: @photo_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_restaurants/1
  # DELETE /photo_restaurants/1.json
  def destroy
    @photo_restaurant.destroy
    respond_to do |format|
      format.html { redirect_to photo_restaurants_url, notice: 'Photo restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_restaurant
      @photo_restaurant = PhotoRestaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_restaurant_params
      params.require(:photo_restaurant).permit(:image_url, :restaurant_id)
    end
end

app/helpers/photo_restaurants_helper.rb
module PhotoRestaurantsHelper
end

app/views/photo_restaurants/_form.html.erb
<%= form_with(model: photo_restaurant, local: true) do |form| %>
  <% if photo_restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo_restaurant.errors.count, "error") %> prohibited this photo_restaurant from being saved:</h2>

      <ul>
      <% photo_restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :restaurant_id %>
    <%= form.text_field :restaurant_id, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photo_restaurants/edit.html.erb
<% if signed_in? %>
<h1>Editing Photo Restaurant</h1>

<%= render 'form', photo_restaurant: @photo_restaurant %>

<%= link_to 'Show', @photo_restaurant %> |
<%= link_to 'Back', photo_restaurants_path %>

<% end %>

app/views/photo_restaurants/index.html.erb
<% if signed_in? %>
<p id="notice"><%= notice %></p>

<h1>Photo Restaurants</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Image url</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photo_restaurants.each do |photo_restaurant| %>
      <tr>
        <td><%= photo_restaurant.image_url %></td>
        <td><%= photo_restaurant.restaurant.name %></td>
        <td><%= link_to 'Show', photo_restaurant %></td>
        <td><%= link_to 'Edit', edit_photo_restaurant_path(photo_restaurant) %></td>
        <td><%= link_to 'Destroy', photo_restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo Restaurant', new_photo_restaurant_path %>

<% end %>

app/views/photo_restaurants/new.html.erb
<% if signed_in? %>
<h1>New Photo Restaurant</h1>

<%= render 'form', photo_restaurant: @photo_restaurant %>

<%= link_to 'Back', photo_restaurants_path %>

<% end %>

app/views/photo_restaurants/show.html.erb
<% if signed_in? %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Image url:</strong>
  <%= @photo_restaurant.image_url %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @photo_restaurant.restaurant.name %>
</p>

<%= link_to 'Edit', edit_photo_restaurant_path(@photo_restaurant) %> |
<%= link_to 'Back', photo_restaurants_path %>

<% end %>